version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1
  node: circleci/node@5.0.2

jobs:
  production:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - node/install:
          node-version: "20.9.0"
      - run: "echo Staging deploy!"
      - add_ssh_keys:
          fingerprints:
            - "fb:98:93:21:e8:f2:17:9d:79:e1:5e:cb:9f:f1:a8:f9"
      - run: "sudo apt-get update && sudo apt-get install -y rsync"
      - run:
          name: "Install NPM packages"
          command: |
            cd app
            npm install
      - run:
          name: "Build assets"
          command: |
            cd app
            npm run build
      - run:
          name: "Staging deploy"
          #command: "rsync -av --delete --exclude-from='rsync-exclude.txt' -e 'ssh -o StrictHostKeychecking=no -p 2222' ~/repo/ pinoko.jp-roughlang@ssh.lolipop.jp:/home/users/2/pinoko.jp-roughlang/web/roughlang.jp/stg/"
      - run:
          name: "Composer"
          #command: "ssh -p 2222 pinoko.jp-roughlang@ssh.lolipop.jp 'cd /home/users/2/pinoko.jp-roughlang/web/roughlang.jp/stg/app;/usr/local/php/8.2/bin/php composer.phar update'"
      - run:
          name: "Optimize"
          #command: "ssh -p 2222 pinoko.jp-roughlang@ssh.lolipop.jp 'cd /home/users/2/pinoko.jp-roughlang/web/roughlang.jp/stg/app;/usr/bin/bash optimizer.sh'"
workflows:
  deploy-workflow:
    jobs:
      - production:
        filters:
          branches:
            only: main
